// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjInputColorExample } from './input.color.example';
export { KjInputExample } from './input.example';
