// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjInputOtpAutosubmitExample } from './input-otp.autosubmit.example';
export { KjInputOtpExample } from './input-otp.example';
export { KjInputOtpLengthsExample } from './input-otp.lengths.example';
export { KjInputOtpMaskedExample } from './input-otp.masked.example';
export { KjInputOtpReactiveExample } from './input-otp.reactive.example';
export { KjInputOtpSeparatorExample } from './input-otp.separator.example';
