// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjButtonGroupExample } from './button-group.example';
export { KjButtonGroupIconOnlyExample } from './button-group.icon-only.example';
export { KjButtonGroupToggleExample } from './button-group.toggle.example';
export { KjButtonGroupVariantsExample } from './button-group.variants.example';
export { KjButtonGroupVerticalExample } from './button-group.vertical.example';
