// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjTextareaAutoresizeExample } from './textarea.autoresize.example';
export { KjTextareaCharacterCountExample } from './textarea.character-count.example';
export { KjTextareaExample } from './textarea.example';
export { KjTextareaNoResizeExample } from './textarea.no-resize.example';
export { KjTextareaUsageExample } from './textarea.usage.example';
export { KjTextareaWithFieldExample } from './textarea.with-field.example';
