// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjPasswordInputExample } from './password-input.example';
export { KjPasswordInputStrengthExample } from './password-input.strength.example';
export { KjPasswordInputToggleExample } from './password-input.toggle.example';
export { KjPasswordInputWithRulesExample } from './password-input.with-rules.example';
