// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { PopoverBasicExample } from './popover.example';
export { PopoverFinanceExample } from './popover.finance.example';
export { PopoverRetroExample } from './popover.retro.example';
