// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjSpeedDialDirectionsExample } from './speed-dial.directions.example';
export { KjSpeedDialDisabledExample } from './speed-dial.disabled.example';
export { KjSpeedDialExample } from './speed-dial.example';
export { KjSpeedDialUsageExample } from './speed-dial.usage.example';
export { KjSpeedDialWithTooltipsExample } from './speed-dial.with-tooltips.example';
