// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { ButtonExample } from './button.example';
export { ButtonFinanceExample } from './button.finance.example';
export { ButtonRetroExample } from './button.retro.example';
export { ButtonSizesExample } from './button.sizes.example';
