// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjBreadcrumbCustomSeparatorExample } from './breadcrumb.custom-separator.example';
export { KjBreadcrumbExample } from './breadcrumb.example';
export { KjBreadcrumbLongPathExample } from './breadcrumb.long-path.example';
export { KjBreadcrumbTruncatedExample } from './breadcrumb.truncated.example';
export { KjBreadcrumbWithIconsExample } from './breadcrumb.with-icons.example';
