// AUTO-GENERATED by scripts/migrate-examples.mjs (manually augmented)
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjIconGalleryExample } from './icon.gallery.example';
export { KjIconUsageExample } from './icon.usage.example';
