// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { MotionExample } from './motion.example';
export { MotionReducedExample } from './motion.reduced.example';
