// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjTypographyBlockquoteExample } from './typography.blockquote.example';
export { KjTypographyCodeExample } from './typography.code.example';
export { KjTypographyExample } from './typography.example';
export { KjTypographyLeadExample } from './typography.lead.example';
export { KjTypographyMutedExample } from './typography.muted.example';
export { KjTypographyTruncateExample } from './typography.truncate.example';
export { KjTypographyUsageExample } from './typography.usage.example';
