// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjAvatarDefaultExample } from './avatar.default.example';
export { KjAvatarGroupExample } from './avatar-group.example';
export { KjAvatarGroupListExample } from './avatar-group.list.example';
export { KjAvatarGroupOverflowExample } from './avatar-group.overflow.example';
export { KjAvatarGroupShapesExample } from './avatar-group.shapes.example';
export { KjAvatarGroupSizesExample } from './avatar-group.sizes.example';
export { KjAvatarInitialsExample } from './avatar.initials.example';
export { KjAvatarShapesExample } from './avatar.shapes.example';
export { KjAvatarSizesExample } from './avatar.sizes.example';
export { KjAvatarWithImageExample } from './avatar.with-image.example';
