// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjOverlayBadgeDescribedExample } from './overlay-badge.described.example';
export { KjOverlayBadgeDotExample } from './overlay-badge.dot.example';
export { KjOverlayBadgeExample } from './overlay-badge.example';
export { KjOverlayBadgeOnAvatarExample } from './overlay-badge.on-avatar.example';
export { KjOverlayBadgePositionsExample } from './overlay-badge.positions.example';
