// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjBadgeDefaultExample } from './badge.default.example';
export { KjBadgeSizesExample } from './badge.sizes.example';
export { KjBadgeVariantsExample } from './badge.variants.example';
export { KjBadgeWithDotExample } from './badge.with-dot.example';
export { KjBadgeWithIconExample } from './badge.with-icon.example';
