// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjProgressBarExample } from './progress-bar.example';
export { KjProgressBarIndeterminateExample } from './progress-bar.indeterminate.example';
export { KjProgressBarSizesExample } from './progress-bar.sizes.example';
export { KjProgressBarVariantsExample } from './progress-bar.variants.example';
export { KjProgressBarWithLabelExample } from './progress-bar.with-label.example';
