// Generated by scripts/sync-version.mjs from package.json — do not edit by hand.

/** Version of the installed `@kouji-ui/components` package, as published to npm. */
export const KJ_COMPONENTS_VERSION = '0.10.0';
