// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { ToastBasicExample } from './toast.example';
export { ToastFinanceExample } from './toast.finance.example';
export { ToastRetroExample } from './toast.retro.example';
