// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjTableColumnPinningExample } from './table.column-pinning.example';
export { KjTableColumnResizeExample } from './table.column-resize.example';
export { KjTableColumnVisibilityExample } from './table.column-visibility.example';
export { KjTableDensityExample } from './table.density.example';
export { KjTableEditableExample } from './table.editable.example';
export { KjTableEmptyAndErrorExample } from './table.empty-and-error.example';
export { KjTableExample } from './table.example';
export { KjTableExportExample } from './table.export.example';
export { KjTableFilterableExample } from './table.filterable.example';
export { KjTableGroupingExample } from './table.grouping.example';
export { KjTableKeyboardExample } from './table.keyboard.example';
export { KjTableMasterDetailExample } from './table.master-detail.example';
export { KjTablePersistenceExample } from './table.persistence.example';
export { KjTablePlayground } from './table.playground';
export { KjTableRowPinningExample } from './table.row-pinning.example';
export { KjTableSelectionExample } from './table.selection.example';
export { KjTableServerModeExample } from './table.server-mode.example';
export { KjTableSortableExample } from './table.sortable.example';
export { KjTableThemingExample } from './table.theming.example';
export { KjTableUsageExample } from './table.usage.example';
export { KjTableVirtualizedExample } from './table.virtualized.example';
