// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjActionSheetExample } from './action-sheet.example';
export { KjActionSheetIconsExample } from './action-sheet.icons.example';
