// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjNumberInputCurrencyExample } from './number-input.currency.example';
export { KjNumberInputDecimalExample } from './number-input.decimal.example';
export { KjNumberInputExample } from './number-input.example';
export { KjNumberInputMinMaxExample } from './number-input.min-max.example';
export { KjNumberInputWithStepperExample } from './number-input.with-stepper.example';
