// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjDateRangePresetsCustomExample } from './date-range-presets.custom.example';
export { KjDateRangePresetsExample } from './date-range-presets.basic.example';
