// AUTO-GENERATED by scripts/migrate-examples.mjs
// Map of folder → lazy loader for that folder's example components,
// plus a static exportName → folder owner index.
//
// Consumers (apps/docs ExampleRegistryService) look up an export name in
// EXAMPLE_OWNER to find its folder chunk, then call EXAMPLE_LOADERS[folder]()
// to import the (code-split) module containing it.
//
// Each entry below produces its own chunk in the build output — opening
// the docs page for component X only pulls component X's examples, not the
// entire library.

import type { Type } from '@angular/core';

export const EXAMPLE_LOADERS: Record<string, () => Promise<Record<string, Type<unknown>>>> = {
  'button': () => import('./button/_examples') as Promise<Record<string, Type<unknown>>>,
  'chart': () => import('./chart/_examples') as Promise<Record<string, Type<unknown>>>,
  'dialog': () => import('./dialog/_examples') as Promise<Record<string, Type<unknown>>>,
  'motion': () => import('./motion/_examples') as Promise<Record<string, Type<unknown>>>,
  'i18n': () => import('./i18n/_examples') as Promise<Record<string, Type<unknown>>>,
  'locale': () => import('./locale/_examples') as Promise<Record<string, Type<unknown>>>,
  'popover': () => import('./popover/_examples') as Promise<Record<string, Type<unknown>>>,
  'toast': () => import('./toast/_examples') as Promise<Record<string, Type<unknown>>>,
  'tooltip': () => import('./tooltip/_examples') as Promise<Record<string, Type<unknown>>>,
};

export const EXAMPLE_OWNER: Record<string, string> = {
  ButtonExample: 'button',
  ButtonFinanceExample: 'button',
  ButtonRetroExample: 'button',
  ButtonSizesExample: 'button',
  ChartAreaExample: 'chart',
  ChartBarExample: 'chart',
  ChartDonutExample: 'chart',
  ChartEventsExample: 'chart',
  ChartExample: 'chart',
  ChartFallbackExample: 'chart',
  ChartLoadingExample: 'chart',
  ChartPluggableExample: 'chart',
  ChartSparklineExample: 'chart',
  DialogBasicExample: 'dialog',
  DialogConfirmExample: 'dialog',
  DialogFinanceExample: 'dialog',
  DialogRetroExample: 'dialog',
  MotionExample: 'motion',
  MotionReducedExample: 'motion',
  I18nBasicExample: 'i18n',
  LocaleBasicExample: 'locale',
  PopoverBasicExample: 'popover',
  PopoverFinanceExample: 'popover',
  PopoverRetroExample: 'popover',
  ToastBasicExample: 'toast',
  ToastFinanceExample: 'toast',
  ToastRetroExample: 'toast',
  TooltipBasicExample: 'tooltip',
  TooltipFinanceExample: 'tooltip',
  TooltipPlacementsExample: 'tooltip',
  TooltipRetroExample: 'tooltip',
};
