// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjSpinnerAnimationsExample } from './spinner.animations.example';
export { KjSpinnerExample } from './spinner.example';
export { KjSpinnerInButtonExample } from './spinner.in-button.example';
export { KjSpinnerSizesExample } from './spinner.sizes.example';
export { KjSpinnerUsageExample } from './spinner.usage.example';
export { KjSpinnerVariantsExample } from './spinner.variants.example';
