// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { AiChatExample } from './ai-chat.streaming.example';
export { KjChatBubbleExample } from './chat-bubble.example';
export { KjChatBubbleGroupedExample } from './chat-bubble.grouped.example';
export { KjChatBubbleSidesExample } from './chat-bubble.sides.example';
export { KjChatBubbleVariantsExample } from './chat-bubble.variants.example';
export { KjChatBubbleWithStateExample } from './chat-bubble.with-state.example';
