// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjMenubarDisabledItemExample } from './menubar.disabled-item.example';
export { KjMenubarExample } from './menubar.example';
export { KjMenubarWithShortcutsExample } from './menubar.with-shortcuts.example';
export { KjMenubarWithSubmenuExample } from './menubar.with-submenu.example';
