// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjSkeletonAnimationsExample } from './skeleton.animations.example';
export { KjSkeletonCardExample } from './skeleton.card.example';
export { KjSkeletonExample } from './skeleton.example';
export { KjSkeletonShapesExample } from './skeleton.shapes.example';
