// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjTabsControlledExample } from './tabs.controlled.example';
export { KjTabsDisabledExample } from './tabs.disabled.example';
export { KjTabsExample } from './tabs.example';
export { KjTabsManualActivationExample } from './tabs.manual-activation.example';
export { KjTabsUsageExample } from './tabs.usage.example';
export { KjTabsVerticalExample } from './tabs.vertical.example';
