// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjCardCoverExample } from './card.cover.example';
export { KjCardExample } from './card.example';
export { KjCardFullExample } from './card.full.example';
