// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjSliderExample } from './slider.example';
export { KjSliderFormattedExample } from './slider.formatted.example';
export { KjSliderRangeExample } from './slider.range.example';
export { KjSliderVerticalExample } from './slider.vertical.example';
export { KjSliderWithMarksExample } from './slider.with-marks.example';
