// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjCarouselAutoplayExample } from './carousel.autoplay.example';
export { KjCarouselExample } from './carousel.example';
export { KjCarouselIndicatorsExample } from './carousel.indicators.example';
export { KjCarouselLazyLoadExample } from './carousel.lazy-load.example';
export { KjCarouselTabsPatternExample } from './carousel.tabs-pattern.example';
