// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjDialogConfirmationExample } from './dialog.confirmation.example';
export { KjDialogDefaultExample } from './dialog.default.example';
export { KjDialogNestedExample } from './dialog.nested.example';
export { KjDialogScrollableExample } from './dialog.scrollable.example';
export { KjDialogUsageExample } from './dialog.usage.example';
export { KjDialogWithFormExample } from './dialog.with-form.example';
