// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjLinkDisabledExample } from './link.disabled.example';
export { KjLinkExample } from './link.example';
export { KjLinkExternalExample } from './link.external.example';
export { KjLinkInProseExample } from './link.in-prose.example';
export { KjLinkSizesExample } from './link.sizes.example';
export { KjLinkVariantsExample } from './link.variants.example';
