// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjPaginationBoundariesExample } from './pagination.boundaries.example';
export { KjPaginationCompactExample } from './pagination.compact.example';
export { KjPaginationExample } from './pagination.example';
export { KjPaginationLargeExample } from './pagination.large.example';
export { KjPaginationWithInfoExample } from './pagination.with-info.example';
