// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjCommandPaletteAsyncExample } from './command-palette.async.example';
export { KjCommandPaletteDialogExample } from './command-palette.dialog.example';
export { KjCommandPaletteExample } from './command-palette.example';
export { KjCommandPaletteFuzzyExample } from './command-palette.fuzzy.example';
export { KjCommandPaletteGroupsExample } from './command-palette.groups.example';
export { KjCommandPaletteUsageExample } from './command-palette.usage.example';
