// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { DialogBasicExample } from './dialog.example';
export { DialogConfirmExample } from './dialog.confirm.example';
export { DialogFinanceExample } from './dialog.finance.example';
export { DialogRetroExample } from './dialog.retro.example';
