// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjTimePicker12HourExample } from './time-picker.12-hour.example';
export { KjTimePickerExample } from './time-picker.example';
export { KjTimePickerFormattedExample } from './time-picker.formatted.example';
export { KjTimePickerRangeExample } from './time-picker.range.example';
export { KjTimePickerUsageExample } from './time-picker.usage.example';
export { KjTimePickerWithSecondsExample } from './time-picker.with-seconds.example';
