// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjKbdComboExample } from './kbd.combo.example';
export { KjKbdExample } from './kbd.example';
export { KjKbdInTooltipExample } from './kbd.in-tooltip.example';
export { KjKbdSizesExample } from './kbd.sizes.example';
