// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjFieldDisabledExample } from './field.disabled.example';
export { KjFieldExample } from './field.example';
export { KjFieldRequiredExample } from './field.required.example';
export { KjFieldWithErrorExample } from './field.with-error.example';
export { KjFieldWithPrefixSuffixExample } from './field.with-prefix-suffix.example';
