// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjAlertBannerExample } from './alert.banner.example';
export { KjAlertDismissibleExample } from './alert.dismissible.example';
export { KjAlertExample } from './alert.example';
export { KjAlertVariantsExample } from './alert.variants.example';
export { KjAlertWithActionsExample } from './alert.with-actions.example';
