// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { TooltipBasicExample } from './tooltip.example';
export { TooltipFinanceExample } from './tooltip.finance.example';
export { TooltipPlacementsExample } from './tooltip.placements.example';
export { TooltipRetroExample } from './tooltip.retro.example';
