#!/usr/bin/env node
/**
 * Keeps `packages/components/src/version.ts` in step with the package's
 * `package.json`, so the published `KJ_COMPONENTS_VERSION` constant can never
 * drift from the version npm reports.
 *
 * Runs before every components build (`pnpm --filter @kouji-ui/components build`)
 * and after `changeset version` (`pnpm version-packages`), so the generated file
 * is committed alongside each version bump. `version.spec.ts` asserts the two
 * agree; CI additionally runs `--check`, which exits non-zero instead of
 * writing when the committed file is stale.
 *
 * Usage: node scripts/sync-version.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const TARGETS = [
  {
    name: 'KJ_COMPONENTS_VERSION',
    pkg: new URL('../packages/components/package.json', import.meta.url),
    out: new URL('../packages/components/src/version.ts', import.meta.url),
    doc: 'Version of the installed `@kouji-ui/components` package, as published to npm.',
  },
];

const check = process.argv.includes('--check');
let stale = 0;

for (const { name, pkg, out, doc } of TARGETS) {
  const { version } = JSON.parse(readFileSync(pkg, 'utf8'));
  const expected =
    `// Generated by scripts/sync-version.mjs from package.json — do not edit by hand.\n\n` +
    `/** ${doc} */\n` +
    `export const ${name} = '${version}';\n`;

  let current = null;
  try {
    current = readFileSync(out, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    // First run: the file does not exist yet.
  }

  if (current === expected) {
    console.log(`${name} = ${version} (up to date)`);
    continue;
  }
  if (check) {
    stale += 1;
    console.error(
      `${fileURLToPath(out)} is stale for ${name} = ${version}; run: pnpm sync-version`,
    );
    continue;
  }
  writeFileSync(out, expected);
  console.log(`${name} = ${version} (wrote ${fileURLToPath(out)})`);
}

if (stale > 0) process.exit(1);
