// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjInputGroupButtonExample } from './input-group.button.example';
export { KjInputGroupExample } from './input-group.example';
export { KjInputGroupIconExample } from './input-group.icon.example';
export { KjInputGroupUrlExample } from './input-group.url.example';
export { KjInputGroupVariantsExample } from './input-group.variants.example';
