// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjDrawerExample } from './drawer.example';
export { KjDrawerModalVsNonModalExample } from './drawer.modal-vs-non-modal.example';
export { KjDrawerScrollableExample } from './drawer.scrollable.example';
export { KjDrawerSidesExample } from './drawer.sides.example';
export { KjDrawerUsageExample } from './drawer.usage.example';
export { KjDrawerWithFormExample } from './drawer.with-form.example';
