// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjSelectDefaultExample } from './select.default.example';
export { KjSelectDisabledExample } from './select.disabled.example';
export { KjSelectGroupedExample } from './select.grouped.example';
export { KjSelectPlaceholderExample } from './select.placeholder.example';
