// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjColorPickerAlphaExample } from './color-picker.alpha.example';
export { KjColorPickerExample } from './color-picker.example';
export { KjColorPickerHexInputExample } from './color-picker.hex-input.example';
export { KjColorPickerInFormExample } from './color-picker.in-form.example';
export { KjColorPickerUsageExample } from './color-picker.usage.example';
export { KjColorPickerWithPresetsExample } from './color-picker.with-presets.example';
