// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjFormAsyncSubmitExample } from './form.async-submit.example';
export { KjFormCompoundExample } from './form.compound.example';
export { KjFormExample } from './form.example';
export { KjFormValidationExample } from './form.validation.example';
