// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjConfirmPopupDestructiveExample } from './confirm-popup.destructive.example';
export { KjConfirmPopupExample } from './confirm-popup.example';
export { KjConfirmPopupPlacementExample } from './confirm-popup.placement.example';
export { KjConfirmPopupUsageExample } from './confirm-popup.usage.example';
export { KjConfirmPopupWithMessageExample } from './confirm-popup.with-message.example';
