// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjPopoverCancellableExample } from './popover.cancellable.example';
export { KjPopoverExample } from './popover.example';
export { KjPopoverModalExample } from './popover.modal.example';
export { KjPopoverSidesExample } from './popover.sides.example';
export { KjPopoverWithFormExample } from './popover.with-form.example';
