// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjSheetExample } from './sheet.example';
export { KjSheetDetentsExample } from './sheet.detents.example';
export { KjSheetScrollableExample } from './sheet.scrollable.example';
