// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjChartDonutExample } from './chart.donut.example';
export { KjChartExample } from './chart.example';
export { KjChartUsageExample } from './chart.usage.example';
