// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjAccordionDefaultExample } from './accordion.default.example';
export { KjAccordionDisabledExample } from './accordion.disabled.example';
export { KjAccordionMultipleExample } from './accordion.multiple.example';
export { KjAccordionRichContentExample } from './accordion.rich-content.example';
