// AUTO-GENERATED by scripts/migrate-examples.mjs
// One barrel per component folder — used by the docs app as a lazy chunk.
export { KjButtonAnchorExample } from './button.anchor.example';
export { KjButtonConfiguredExample } from './button.configured.example';
export { KjButtonDisabledExample } from './button.disabled.example';
export { KjButtonExample } from './button.example';
export { KjButtonIconExample } from './button.icon.example';
export { KjButtonLoadingExample } from './button.loading.example';
export { KjButtonPressedExample } from './button.pressed.example';
export { KjButtonSizesExample } from './button.sizes.example';
export { KjButtonUsageExample } from './button.usage.example';
export { KjButtonVariantsExample } from './button.variants.example';
